### ISSUE TITLE
Tuner.h fails to compile with g++ 14.2.0

### ISSUE THREAD

**Issue by folkertvanheusden** [Mk-Chan/libchess#25]
`test.cpp` is like this:

```
#include "Tuner.h"

int main(int argc, char *argv[])
{
	return 0;
}
```

error given:

```
In file included from test.cpp:1:
Tuner.h: In static member function ‘static std::vector<libchess::NormalizedResult<Position> > libchess::NormalizedResult<Position>::parse_epd(const std::string&, std::function<Position(const std::__cxx11::basic_string<char>&)>, const std::string&)’:
Tuner.h:101:37: error: no matching function for call to ‘find(const char*, std::basic_string_view<char>::const_iterator, char)’
  101 |                 curr_pos = std::find(curr_pos + 1, line_view.end(), ' ');
      |                            ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by folkertvanheusden** [comment]
Fixed in https://github.com/Mk-Chan/libchess/pull/26
